version: "3"
services:
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]

volumes:
  dbdata:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
